baseurl = "https://decarbdirect.com/" # Configure URL.
title = "Decarb Direct Partners"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
[languages]
	[languages.en]
		languageName = "English"
		contentDir = "content/en"
		weight = 1

	[languages.vi]
		languageName = "Vietnamese"
		contentDir = "content/vi"
		weight = 2

	[languages.vi.params]
  		disqusshortname = ""
  		googleanalytics = ""


# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[languages.en.menu.main]]
    name       = "Products"
    identifier = "menu.products"
    url        = "/products"
    weight     = 1

[[languages.en.menu.main]]
    name       = "GHG Dashboard"
    url        = "/products/dashboard"
    weight     = 11
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Analytics"
    url        = "/products/analytics"
    weight     = 12
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Reporting"
    url        = "/products/reporting"
    weight     = 13
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/products/solutions"
    weight     = 14
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Resources"
    url        = "/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.en.menu.main]]
    name       = "Regulatory Updates"
    url        = "/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb Guidelines"
    url        = "/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Case studies"
    url        = "/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb News"
    url        = "/decarbnews/"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.en.menu.main]]
    name       = "About us"
    identifier = "menu.aboutus"
    url        = "/aboutus/"
    weight     = 4

[[languages.en.menu.main]]
    name       = "Mission & Vision"
    url        = "/aboutus/mission"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Partnership"
    url        = "/aboutus/partnership"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Contact us"
    url        = "/aboutus/contact"
    weight     = 43
    parent     = "menu.aboutus"

#Vietnamese main menu

[[languages.vi.menu.main]]
    name       = "Sản phẩm"
    identifier = "menu.products"
    url        = "/vi/products"
    weight     = 1

[[languages.vi.menu.main]]
    name       = "GHG Dashboard"
    url        = "/vi/products/dashboard"
    weight     = 11
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Analytics"
    url        = "/vi/products/analytics"
    weight     = 12
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Reporting"
    url        = "/vi/products/reporting"
    weight     = 13
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/vi/products/solutions"
    weight     = 14
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Thư viện"
    url        = "/vi/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.vi.menu.main]]
    name       = "Chính sách & quy định mới"
    url        = "/vi/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Sổ tay hướng dẫn"
    url        = "/vi/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Case studies"
    url        = "/vi/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Decarb News"
    url        = "/vi/decarbnews/"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.vi.menu.main]]
    name       = "Về Decarb Direct"
    identifier = "menu.aboutus"
    url        = "/vi/aboutus/"
    weight     = 4

[[languages.vi.menu.main]]
    name       = "Sứ mệnh & Tầm nhìn"
    url        = "/vi/aboutus/mission"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Hợp tác"
    url        = "/vi/aboutus/partnership"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Liên hệ"
    url        = "/vi/aboutus/contact"
    weight     = 43
    parent     = "menu.aboutus"




#[[menu.topbar]]
#    weight = 1
#    name = "Phone"
#   url = "tel:+84 912 345 678"
#    pre = "<i class='fas fa-2x fa-phone'></i>"


#[[menu.topbar]]
#    weight = 5
#    name = "Email"
#    url = "mailto:info@decarbdirect.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/decarbnews/"
    author = "ddp"
    defaultKeywords = ["decarbonization", "update", "GHG news"]
    mainSections = ["decarbnews"]
    defaultDescription = "Stay informed on global climate policy, sustainable development initiatives, and progress in mitigating climate change."

    # Social media
    # facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    # twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    # default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    # enableGoogleMaps = true
    # googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    # latitude = "-12.043333"
    # longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
     formspree_action = "https://formspree.io/f/mvoeyrbg"
     contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Your partner in decarbonization journey</p>"
    copyright = "Copyright (c) 2024, Decarb Direct Partners, all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = true

    disabled_logo = false
    logo_text = "Decarb Direct Partners"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Decarb Direct Partners</strong>
        <br>Hanoi
        <br>Vietnam
        </p>
      """

[permalinks]
	regulatory = "/regulatory/:year/:month/:day/:filename/"
 	guidelines = "/guidelines/:year/:month/:day/:filename/"
  	cases = "/cases/:year/:month/:day/:filename/"
    decarbnews = "/decarbnews/:year/:month/:day/:filename/"


# Enable or disable top bar with social icons
#[params.topbar]
#    enable = false
#    text = """<p class="hidden-sm hidden-xs">Contact us on +84 912 345 678 or info@decarbdirect.com.</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:info@decarbdirect.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

# [params.carouselCustomers]
#    items = 6
#    auto_play = false
#    slide_speed = 2000
#    pagination_speed = 1000

# [params.carouselTestimonials]
#    items = 4
#    auto_play = false
#    slide_speed = 2000
#    pagination_speed = 1000

# [params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
#    enable = true
#    auto_play = true
#    slide_speed = 2000
#    pagination_speed = 1000

[params.features]
    enable = true
    cols = 2 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

#[params.testimonials]
 #   enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    # title = "Testimonials"
    #subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

# [params.see_more]
#    enable = true
 #   icon = "far fa-file-alt"
  #  title = "Do you want to see more?"
   # subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    #link_url = "#"
    #link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From Decarb News"
    subtitle = "Stay informed on global climate policy, sustainable development initiatives, and progress in mitigating climate change."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  
